# Generated by Django 4.2.5 on 2023-09-22 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=250)),
                ('beds', models.CharField(max_length=240)),
                ('image', models.ImageField(upload_to='')),
                ('bathroom', models.CharField(max_length=60)),
                ('garage', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('property_ID', models.CharField(max_length=30)),
                ('property_Type', models.CharField(max_length=50)),
                ('property_Status', models.CharField(max_length=70)),
                ('rooms', models.CharField(max_length=50)),
                ('year_built', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
