# Generated by Django 4.2.5 on 2023-09-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_feature_property_for_rent_or_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='house_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
