# Generated by Django 4.2.5 on 2023-09-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_retype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
