# Generated by Django 4.2.5 on 2023-10-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_user_password_retype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('event_name', models.CharField(max_length=200)),
                ('event_time', models.TimeField()),
                ('num_visitors', models.IntegerField()),
                ('property_title', models.CharField(max_length=200)),
            ],
        ),
    ]
