# Generated by Django 4.2.5 on 2023-10-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_user_password_retype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='calendly_user_name_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
