# Generated by Django 4.2.5 on 2023-10-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_user_calendly_user_name_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='legal_information',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='links_to_legal_documents',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='property',
            name='visitation_days',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
